/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compagnie.compagnieaeriennemongodb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author flo
 */
public class JfAeroports extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    
    /**
     * Creates new form JfAeroports
     */
    public JfAeroports() {
        initComponents();
        tableUpdate();
    }
    
    public void tableUpdate(){
        
        int cpt;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("select * from aeroport");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData(); //Recupération des données sql
            
            cpt = rsmd.getColumnCount();
            
            DefaultTableModel dtm = (DefaultTableModel)tableAeroports.getModel();
            
            dtm.setRowCount(0);
            
            while(rs.next()) {
                
                Vector vect = new Vector();
                
                for (int i = 0; i < cpt; i++) {
                    vect.add(rs.getString("idaeroport"));
                    vect.add(rs.getString("nom"));
                    vect.add(rs.getString("ville"));
                    vect.add(rs.getString("pays"));
                }
                dtm.addRow(vect);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getBtnAddAeroport(){
        
    }
    
    public void getBtnUpdateAeroport(){
        
    }
    
    public void getBtnDeleteAeroport(){
    }

    public JTextField getInputNameAeroport() {
        return inputNameAeroport;
    }

    public JTextField getInputPaysAeroport() {
        return inputPaysAeroport;
    }

    public JTextField getInputVilleAeroport() {
        return inputVilleAeroport;
    }

    public JTable getTableAeroports() {
        return tableAeroports;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputNameAeroport = new javax.swing.JTextField();
        inputVilleAeroport = new javax.swing.JTextField();
        inputPaysAeroport = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAjouterAeroport = new javax.swing.JButton();
        btnModifierAeroport = new javax.swing.JButton();
        btnSupprimerAeroport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputIdAeroport = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAeroports = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        inputNameAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameAeroportActionPerformed(evt);
            }
        });

        inputVilleAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVilleAeroportActionPerformed(evt);
            }
        });

        inputPaysAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPaysAeroportActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Ville");

        jLabel3.setText("Pays");

        btnAjouterAeroport.setText("Ajouter");
        btnAjouterAeroport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterAeroportMouseClicked(evt);
            }
        });
        btnAjouterAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterAeroportActionPerformed(evt);
            }
        });

        btnModifierAeroport.setText("Modifier");
        btnModifierAeroport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierAeroportMouseClicked(evt);
            }
        });
        btnModifierAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierAeroportActionPerformed(evt);
            }
        });

        btnSupprimerAeroport.setText("Supprimer");
        btnSupprimerAeroport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimerAeroportMouseClicked(evt);
            }
        });
        btnSupprimerAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerAeroportActionPerformed(evt);
            }
        });

        jLabel4.setText("Id");

        inputIdAeroport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdAeroportActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPaysAeroport)
                    .addComponent(inputVilleAeroport)
                    .addComponent(inputNameAeroport)
                    .addComponent(inputIdAeroport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModifierAeroport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouterAeroport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupprimerAeroport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputIdAeroport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNameAeroport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputVilleAeroport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPaysAeroport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAjouterAeroport)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifierAeroport)
                        .addGap(24, 24, 24)
                        .addComponent(btnSupprimerAeroport)))
                .addGap(55, 55, 55))
        );

        btnAjouterAeroport.getAccessibleContext().setAccessibleDescription("");

        tableAeroports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Ville", "Pays"
            }
        ));
        tableAeroports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAeroportsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableAeroports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupprimerAeroportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimerAeroportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerAeroportMouseClicked

    private void btnAjouterAeroportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterAeroportMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAjouterAeroportMouseClicked

    private void btnModifierAeroportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierAeroportMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnModifierAeroportMouseClicked

    private void tableAeroportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAeroportsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tableAeroports.getModel();
        int selectedIndex = tableAeroports.getSelectedRow();
        
        inputIdAeroport.setText(dtm.getValueAt(selectedIndex, 0).toString());
        inputNameAeroport.setText(dtm.getValueAt(selectedIndex, 1).toString());
        inputVilleAeroport.setText(dtm.getValueAt(selectedIndex, 2).toString());
        inputPaysAeroport.setText(dtm.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_tableAeroportsMouseClicked

    private void inputNameAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameAeroportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameAeroportActionPerformed

    private void inputVilleAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVilleAeroportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVilleAeroportActionPerformed

    private void inputPaysAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPaysAeroportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPaysAeroportActionPerformed

    private void btnSupprimerAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerAeroportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tableAeroports.getModel();
        int selectedIndex = tableAeroports.getSelectedRow();
            
        int idAerop = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette donnée ?", "Attention !", JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_OPTION)
        {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("delete from aeroport where idaeroport=?");

                pst.setInt(1, idAerop);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Donnée supprimée!");

                inputNameAeroport.setText("");
                inputVilleAeroport.setText("");
                inputPaysAeroport.setText("");

                tableUpdate();
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerAeroportActionPerformed

    private void btnModifierAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierAeroportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tableAeroports.getModel();
        int selectedIndex = tableAeroports.getSelectedRow();
        
        try {
            
            int idAerop = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
            String nomAeroport = inputNameAeroport.getText();
            String villeAeroport = inputVilleAeroport.getText(); 
            String paysAeroport = inputPaysAeroport.getText(); 
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("update aeroport set nom = ?, ville = ?, pays = ? where idaeroport = ?");
            
            pst.setString(1, nomAeroport);
            pst.setString(2, villeAeroport);
            pst.setString(3, paysAeroport);
            pst.setInt(4, idAerop);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données mises à jour !");
            
            inputNameAeroport.setText("");
            inputVilleAeroport.setText("");
            inputPaysAeroport.setText("");
            
            tableUpdate();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifierAeroportActionPerformed

    private void btnAjouterAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterAeroportActionPerformed
        // TODO add your handling code here:
        if(inputNameAeroport.getText().equals("") || inputVilleAeroport.getText().equals("") || inputPaysAeroport.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vous devez remplir les champs !", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);;
            inputIdAeroport.requestFocus();
            inputNameAeroport.requestFocus();
            inputVilleAeroport.requestFocus();
            inputPaysAeroport.requestFocus();
        } else {
            String idAeroport = inputIdAeroport.getText();
            String nomAeroport = inputNameAeroport.getText();
            String villeAeroport = inputVilleAeroport.getText();
            String paysAeroport = inputPaysAeroport.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("insert into aeroport (idaeroport, nom, ville, pays) values (?,?,?,?)");
                pst.setString(1,idAeroport);
                pst.setString(2,nomAeroport);
                pst.setString(3,villeAeroport);
                pst.setString(4,paysAeroport);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Données enregistrées !");
                
                inputIdAeroport.setText("");
                inputNameAeroport.setText("");
                inputVilleAeroport.setText("");
                inputPaysAeroport.setText("");

                tableUpdate();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAjouterAeroportActionPerformed

    private void inputIdAeroportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdAeroportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdAeroportActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        PagePrincipale r = new PagePrincipale();
        r.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfAeroports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfAeroports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfAeroports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfAeroports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfAeroports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterAeroport;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModifierAeroport;
    private javax.swing.JButton btnSupprimerAeroport;
    private javax.swing.JTextField inputIdAeroport;
    private javax.swing.JTextField inputNameAeroport;
    private javax.swing.JTextField inputPaysAeroport;
    private javax.swing.JTextField inputVilleAeroport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableAeroports;
    // End of variables declaration//GEN-END:variables
    
}
