/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compagnie.compagnieaeriennemongodb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author flo
 */
public class JfCompagnies extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    
    /**
     * Creates new form JfCompagnies
     */
    public JfCompagnies() {
        initComponents();
        setLocationRelativeTo(null);
        tableUpdate();
    }
    
    private void tableUpdate(){
        
        int cpt;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("select * from compagnie");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData(); //Recupération des données sql
            
            cpt = rsmd.getColumnCount();
            
            DefaultTableModel dtm = (DefaultTableModel)tableCompagnie.getModel();
            
            dtm.setRowCount(0);
            
            while(rs.next()) {
                
                Vector vect = new Vector();
                
                for (int i = 0; i < cpt; i++) {
                    vect.add(rs.getString("idcompagnie"));
                    vect.add(rs.getString("nom"));
                }
                dtm.addRow(vect);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputNameCompagnies = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAjouterCompagnies = new javax.swing.JButton();
        btnModifierCompagnies = new javax.swing.JButton();
        btnSupprimerCompagnies = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputIdCompagnies = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompagnie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jLabel1.setText("Nom");

        btnAjouterCompagnies.setText("Ajouter");
        btnAjouterCompagnies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCompagniesActionPerformed(evt);
            }
        });

        btnModifierCompagnies.setText("Modifier");
        btnModifierCompagnies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCompagniesActionPerformed(evt);
            }
        });

        btnSupprimerCompagnies.setText("Supprimer");
        btnSupprimerCompagnies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerCompagniesActionPerformed(evt);
            }
        });

        jLabel2.setText("Id");

        inputIdCompagnies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdCompagniesActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(41, 41, 41))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputIdCompagnies, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(inputNameCompagnies)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAjouterCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifierCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSupprimerCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMenu)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIdCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNameCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupprimerCompagnies)
                    .addComponent(btnAjouterCompagnies)
                    .addComponent(btnModifierCompagnies))
                .addGap(36, 36, 36))
        );

        tableCompagnie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nom"
            }
        ));
        tableCompagnie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCompagnieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCompagnie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterCompagniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCompagniesActionPerformed
        // TODO add your handling code here:
        if(inputNameCompagnies.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vous devez remplir les champs !", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);;
            inputNameCompagnies.requestFocus();
        } else {
            String idCompagnie = inputIdCompagnies.getText();
            String designationCompagnie = inputNameCompagnies.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("insert into compagnie (idcompagnie, nom)" +  "values(?,?)");
                pst.setString(1,idCompagnie);
                pst.setString(2,designationCompagnie);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Données enregistrées !");

                inputNameCompagnies.setText("");

                tableUpdate();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAjouterCompagniesActionPerformed

    private void btnModifierCompagniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCompagniesActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)tableCompagnie.getModel();
        int selectedIndex = tableCompagnie.getSelectedRow();
        
        try {
            
            int idComp = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
            String designComp= inputNameCompagnies.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("update compagnie set nom = ? where idcompagnie = ?");
            
            pst.setString(1, designComp);
            pst.setInt(2, idComp);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données mises à jour !");
            
            inputNameCompagnies.setText("");
            
            tableUpdate();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifierCompagniesActionPerformed

    private void btnSupprimerCompagniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerCompagniesActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)tableCompagnie.getModel();
        int selectedIndex = tableCompagnie.getSelectedRow();
            
        int idComp= Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette donnée ?", "Attention !", JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_OPTION)
        {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("delete from compagnie where idcompagnie=?");

                pst.setInt(1, idComp);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Donnée supprimée!");

                inputNameCompagnies.setText("");

                tableUpdate();
                
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfCompagnies.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerCompagniesActionPerformed

    private void tableCompagnieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCompagnieMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tableCompagnie.getModel();
        int selectedIndex = tableCompagnie.getSelectedRow();
        
        inputIdCompagnies.setText(dtm.getValueAt(selectedIndex, 0).toString());
        inputNameCompagnies.setText(dtm.getValueAt(selectedIndex, 1).toString());
    }//GEN-LAST:event_tableCompagnieMouseClicked

    private void inputIdCompagniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdCompagniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdCompagniesActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        PagePrincipale r = new PagePrincipale();
        r.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfCompagnies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfCompagnies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfCompagnies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfCompagnies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfCompagnies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterCompagnies;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModifierCompagnies;
    private javax.swing.JButton btnSupprimerCompagnies;
    private javax.swing.JTextField inputIdCompagnies;
    private javax.swing.JTextField inputNameCompagnies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCompagnie;
    // End of variables declaration//GEN-END:variables
}
