/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compagnie.compagnieaeriennemongodb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author flo
 */
public class JfPersonnes extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    
    /**
     * Creates new form JfPersonnes
     */
    public JfPersonnes() {
        initComponents();
        tableUpdate();
    }
    
    public void tableUpdate(){
        
        int cpt;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("select * from personne");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData(); //Recupération des données sql
            
            cpt = rsmd.getColumnCount();
            
            DefaultTableModel dtm = (DefaultTableModel)tablePersonnes.getModel();
            
            dtm.setRowCount(0);
            
            while(rs.next()) {
                
                Vector vect = new Vector();
                
                for (int i = 0; i < cpt; i++) {
                    vect.add(rs.getString("idpersonne"));
                    vect.add(rs.getString("nom"));
                    vect.add(rs.getString("prenom"));
                    vect.add(rs.getString("dateNaiss"));
                    vect.add(rs.getString("adresse"));
                    vect.add(rs.getString("ville"));
                    vect.add(rs.getString("zipcode"));
                    vect.add(rs.getString("pays_idPays"));
                }
                dtm.addRow(vect);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNomPersonne = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputDateNaissancePersonne = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputVillePersonne = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPrenomPersonne = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputAdressePersonne = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputZipCodePersonne = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputIdPaysPersonne = new javax.swing.JTextField();
        btnUpdatePersonne = new javax.swing.JButton();
        btnAddPersonne = new javax.swing.JButton();
        btnDeletePersonne = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonnes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jLabel1.setText("Nom");

        jLabel2.setText("DateNaiss");

        jLabel3.setText("Ville");

        jLabel4.setText("Prenom");

        jLabel5.setText("Adresse");

        jLabel6.setText("ZipCode");

        jLabel7.setText("IdPays");

        btnUpdatePersonne.setText("Modifier");
        btnUpdatePersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePersonneActionPerformed(evt);
            }
        });

        btnAddPersonne.setText("Ajouter");
        btnAddPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonneActionPerformed(evt);
            }
        });

        btnDeletePersonne.setText("Supprimer");
        btnDeletePersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePersonneActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(inputIdPaysPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputDateNaissancePersonne)
                                    .addComponent(inputVillePersonne)
                                    .addComponent(inputNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(20, 20, 20)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputZipCodePersonne)
                            .addComponent(inputPrenomPersonne)
                            .addComponent(inputAdressePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnUpdatePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDeletePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(inputPrenomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputDateNaissancePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(inputAdressePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputVillePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(inputZipCodePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputIdPaysPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdatePersonne)
                    .addComponent(btnAddPersonne)
                    .addComponent(btnDeletePersonne))
                .addContainerGap())
        );

        tablePersonnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idPersonne", "Nom", "Prenom", "DateNaiss", "Adresse", "Ville", "ZipCode", "pays_IdPays"
            }
        ));
        tablePersonnes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePersonnesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePersonnes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonneActionPerformed
        // TODO add your handling code here:
        if(inputNomPersonne.getText().equals("") || inputPrenomPersonne.getText().equals("") || inputDateNaissancePersonne.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vous devez remplir les champs !", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);;
            inputNomPersonne.requestFocus();
            inputPrenomPersonne.requestFocus();
            inputDateNaissancePersonne.requestFocus();
            inputAdressePersonne.requestFocus();
            inputVillePersonne.requestFocus();
            inputZipCodePersonne.requestFocus();
            inputIdPaysPersonne.requestFocus();

        } else {
            String nomPersonne = inputNomPersonne.getText();
            String prenomPersonne = inputPrenomPersonne.getText();
            String dateNaissancePersonne = inputDateNaissancePersonne.getText();
            String adressePersonne = inputAdressePersonne.getText();
            String villePersonne = inputVillePersonne.getText();
            String zipCodePersonne = inputZipCodePersonne.getText();
            String idPaysPersonne = inputIdPaysPersonne.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("insert into personne (nom, prenom, dateNaiss, adresse, ville, zipcode, pays_idPays) values (?,?,?,?,?,?,?)");
                pst.setString(1,nomPersonne);
                pst.setString(2,prenomPersonne);
                pst.setString(3,dateNaissancePersonne);
                pst.setString(4,adressePersonne);
                pst.setString(1,villePersonne);
                pst.setString(2,zipCodePersonne);
                pst.setString(3,idPaysPersonne);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Données enregistrées !");
                
                inputNomPersonne.setText("");
                inputPrenomPersonne.setText("");
                inputDateNaissancePersonne.setText("");
                inputAdressePersonne.setText("");
                inputVillePersonne.setText("");
                inputZipCodePersonne.setText("");
                inputIdPaysPersonne.setText("");

                tableUpdate();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfAeroports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddPersonneActionPerformed

    private void btnUpdatePersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonneActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tablePersonnes.getModel();
        int selectedIndex = tablePersonnes.getSelectedRow();
        
        try {
            
            int idPersonne = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
            String nomPersonne = inputNomPersonne.getText();
            String prenomPersonne = inputPrenomPersonne.getText(); 
            String dateNaissPersonne = inputDateNaissancePersonne.getText(); 
            String adressePersonne = inputAdressePersonne.getText();
            String villePersonne = inputVillePersonne.getText(); 
            String zipcodePersonne = inputZipCodePersonne.getText();
            String paysIdPays = inputIdPaysPersonne.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
            pst=con.prepareStatement("update personne set nom = ?, prenom = ?, dateNaiss = ?, adresse = ?, ville = ?, zipcode = ?, pays_idPays = ? where idpersonne = ?");
            
            pst.setString(1, nomPersonne);
            pst.setString(2, prenomPersonne);
            pst.setString(3, dateNaissPersonne);
            pst.setString(4, adressePersonne);
            pst.setString(5, villePersonne);
            pst.setString(6, zipcodePersonne);
            pst.setString(7, paysIdPays);
            pst.setInt(8, idPersonne);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Données mises à jour !");
            
            inputNomPersonne.setText("");
            inputPrenomPersonne.setText("");
            inputDateNaissancePersonne.setText("");
            inputAdressePersonne.setText("");
            inputVillePersonne.setText("");
            inputZipCodePersonne.setText("");
            inputIdPaysPersonne.setText("");
            
            tableUpdate();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JfPersonnes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JfPersonnes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdatePersonneActionPerformed

    private void btnDeletePersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePersonneActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tablePersonnes.getModel();
        int selectedIndex = tablePersonnes.getSelectedRow();
            
        int idAerop = Integer.parseInt(dtm.getValueAt(selectedIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer cette donnée ?", "Attention !", JOptionPane.YES_NO_OPTION);

        if(dialogResult==JOptionPane.YES_OPTION)
        {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con= DriverManager.getConnection("jdbc:mysql://localhost:3307/airbabouche", "root","");
                pst=con.prepareStatement("delete from personne where idpersonne=?");

                pst.setInt(1, idAerop);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Donnée supprimée!");

                inputNomPersonne.setText("");
                inputPrenomPersonne.setText("");
                inputDateNaissancePersonne.setText("");
                inputAdressePersonne.setText("");
                inputVillePersonne.setText("");
                inputZipCodePersonne.setText("");
                inputIdPaysPersonne.setText("");

                tableUpdate();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(JfPersonnes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JfPersonnes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeletePersonneActionPerformed

    private void tablePersonnesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePersonnesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tablePersonnes.getModel();
        int selectedIndex = tablePersonnes.getSelectedRow();
        
        inputNomPersonne.setText(dtm.getValueAt(selectedIndex, 1).toString());
        inputPrenomPersonne.setText(dtm.getValueAt(selectedIndex, 2).toString());
        inputDateNaissancePersonne.setText(dtm.getValueAt(selectedIndex, 3).toString());
        inputAdressePersonne.setText(dtm.getValueAt(selectedIndex, 4).toString());
        inputVillePersonne.setText(dtm.getValueAt(selectedIndex, 5).toString());
        inputZipCodePersonne.setText(dtm.getValueAt(selectedIndex, 6).toString());
        inputIdPaysPersonne.setText(dtm.getValueAt(selectedIndex, 7).toString());
    }//GEN-LAST:event_tablePersonnesMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        PagePrincipale r = new PagePrincipale();
        r.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPersonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPersonnes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPersonne;
    private javax.swing.JButton btnDeletePersonne;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnUpdatePersonne;
    private javax.swing.JTextField inputAdressePersonne;
    private javax.swing.JTextField inputDateNaissancePersonne;
    private javax.swing.JTextField inputIdPaysPersonne;
    private javax.swing.JTextField inputNomPersonne;
    private javax.swing.JTextField inputPrenomPersonne;
    private javax.swing.JTextField inputVillePersonne;
    private javax.swing.JTextField inputZipCodePersonne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePersonnes;
    // End of variables declaration//GEN-END:variables
}
