/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compagnie.compagnieaeriennemongodb;

/**
 *
 * @author flo
 */
public class PagePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form PagePrincipale
     */
    public PagePrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JTextField();
        btnConnexion = new javax.swing.JButton();
        btnInscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReservations = new javax.swing.JButton();
        btnCompagnies = new javax.swing.JButton();
        btnVols = new javax.swing.JButton();
        btnEscales = new javax.swing.JButton();
        btnAeroports = new javax.swing.JButton();
        btnPersonnes = new javax.swing.JButton();
        btnPays = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.gray);

        jLabel2.setText("Email");

        inputEmail.setBackground(java.awt.Color.white);
        inputEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        inputPassword.setBackground(java.awt.Color.white);
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        btnConnexion.setText("Connexion");
        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexionActionPerformed(evt);
            }
        });

        btnInscription.setText("Inscription");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel1.setText("Connection / Inscription");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(inputPassword)))
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnexion)
                    .addComponent(btnInscription))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.Color.gray);

        btnReservations.setBackground(java.awt.Color.white);
        btnReservations.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnReservations.setForeground(java.awt.Color.lightGray);
        btnReservations.setText("Reservations");
        btnReservations.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnReservations.setContentAreaFilled(false);
        btnReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservations.setMaximumSize(new java.awt.Dimension(57, 30));
        btnReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservationsMouseClicked(evt);
            }
        });

        btnCompagnies.setBackground(java.awt.Color.gray);
        btnCompagnies.setText("Compagnies");
        btnCompagnies.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnCompagnies.setContentAreaFilled(false);
        btnCompagnies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompagnies.setMaximumSize(new java.awt.Dimension(57, 30));
        btnCompagnies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompagniesMouseClicked(evt);
            }
        });

        btnVols.setBackground(java.awt.Color.gray);
        btnVols.setText("Vols");
        btnVols.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnVols.setContentAreaFilled(false);
        btnVols.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVols.setMaximumSize(new java.awt.Dimension(57, 30));
        btnVols.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolsMouseClicked(evt);
            }
        });
        btnVols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolsActionPerformed(evt);
            }
        });

        btnEscales.setBackground(java.awt.Color.gray);
        btnEscales.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEscales.setForeground(java.awt.Color.lightGray);
        btnEscales.setText("Escales");
        btnEscales.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnEscales.setContentAreaFilled(false);
        btnEscales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEscales.setMaximumSize(new java.awt.Dimension(57, 30));
        btnEscales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscalesMouseClicked(evt);
            }
        });

        btnAeroports.setBackground(java.awt.Color.gray);
        btnAeroports.setForeground(java.awt.Color.lightGray);
        btnAeroports.setText("Aeroports");
        btnAeroports.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnAeroports.setContentAreaFilled(false);
        btnAeroports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAeroports.setMaximumSize(new java.awt.Dimension(57, 30));
        btnAeroports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAeroportsMouseClicked(evt);
            }
        });

        btnPersonnes.setBackground(java.awt.Color.pink);
        btnPersonnes.setText("Personnes");
        btnPersonnes.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnPersonnes.setContentAreaFilled(false);
        btnPersonnes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonnes.setMaximumSize(new java.awt.Dimension(57, 30));
        btnPersonnes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonnesMouseClicked(evt);
            }
        });

        btnPays.setBackground(java.awt.Color.gray);
        btnPays.setText("Pays");
        btnPays.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true));
        btnPays.setContentAreaFilled(false);
        btnPays.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPays.setMaximumSize(new java.awt.Dimension(57, 30));
        btnPays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaysMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEscales, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnVols, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAeroports, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPersonnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompagnies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscales, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVols, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompagnies, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAeroports, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(btnPays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btnConnexionActionPerformed

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void btnVolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolsActionPerformed

    private void btnReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservationsMouseClicked
        // TODO add your handling code here:
        dispose();
        JfReservations r = new JfReservations();
        r.setVisible(true);
    }//GEN-LAST:event_btnReservationsMouseClicked

    private void btnEscalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscalesMouseClicked
        // TODO add your handling code here:
        dispose();
        JfEscales r = new JfEscales();
        r.setVisible(true);
    }//GEN-LAST:event_btnEscalesMouseClicked

    private void btnAeroportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAeroportsMouseClicked
        // TODO add your handling code here:
        dispose();
        JfAeroports f = new JfAeroports();
        f.setVisible(true);
    }//GEN-LAST:event_btnAeroportsMouseClicked

    private void btnVolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolsMouseClicked
        // TODO add your handling code here:
        dispose();
        JfVols r = new JfVols();
        r.setVisible(true);
    }//GEN-LAST:event_btnVolsMouseClicked

    private void btnPersonnesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonnesMouseClicked
        // TODO add your handling code here:
        dispose();
        JfPersonnes r = new JfPersonnes();
        r.setVisible(true);
    }//GEN-LAST:event_btnPersonnesMouseClicked

    private void btnCompagniesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompagniesMouseClicked
        // TODO add your handling code here:
        dispose();
        JfCompagnies r = new JfCompagnies();
        r.setVisible(true);
    }//GEN-LAST:event_btnCompagniesMouseClicked

    private void btnPaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaysMouseClicked
        // TODO add your handling code here:
        dispose();
        JfPays r = new JfPays();
        r.setVisible(true);
    }//GEN-LAST:event_btnPaysMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAeroports;
    private javax.swing.JButton btnCompagnies;
    private javax.swing.JButton btnConnexion;
    private javax.swing.JButton btnEscales;
    private javax.swing.JButton btnInscription;
    private javax.swing.JButton btnPays;
    private javax.swing.JButton btnPersonnes;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnVols;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
